#!/usr/bin/env python3
"""
Parse nsys stats CSV output and extract key performance ratios.

Usage:
    python3 parse_nsys_stats.py --stats-dir profile/run_name/stats/ [--output profile/run_name/analysis/summary.md]

Expected input files (generated by `nsys stats`):
    - cuda_api_sum.csv
    - cuda_gpu_kern_sum.csv
    - cuda_gpu_mem_time_sum.csv
"""

import argparse
import csv
import os
import sys


def parse_csv(filepath):
    """Parse a CSV file into a list of dicts, skipping comment lines."""
    rows = []
    with open(filepath, "r") as f:
        reader = csv.reader(f)
        header = None
        for row in reader:
            if not row or row[0].startswith("#"):
                continue
            if header is None:
                header = row
                continue
            rows.append(dict(zip(header, row)))
    return rows


def parse_time_ns(time_str):
    """Parse a time string like '1.234 ms' or '567.890 us' to nanoseconds."""
    if not time_str or time_str.strip() == "":
        return 0
    parts = time_str.strip().split()
    if len(parts) != 2:
        return 0
    value = float(parts[0])
    unit = parts[1].lower()
    multipliers = {
        "ns": 1,
        "us": 1000,
        "ms": 1_000_000,
        "s": 1_000_000_000,
    }
    return value * multipliers.get(unit, 1)


def parse_bytes(byte_str):
    """Parse a byte string like '1.234 GB' or '567.890 KB' to bytes."""
    if not byte_str or byte_str.strip() == "":
        return 0
    parts = byte_str.strip().split()
    if len(parts) != 2:
        return 0
    value = float(parts[0])
    unit = parts[1].upper()
    multipliers = {
        "B": 1,
        "KB": 1024,
        "MB": 1024 ** 2,
        "GB": 1024 ** 3,
        "TB": 1024 ** 4,
    }
    return value * multipliers.get(unit, 1)


def analyze(stats_dir, run_name=""):
    """Analyze nsys stats and return a summary dict."""
    summary = {"run_name": run_name}

    # --- Kernel summary ---
    kern_path = os.path.join(stats_dir, "cuda_gpu_kern_sum.csv")
    if os.path.exists(kern_path):
        rows = parse_csv(kern_path)
        total_kern_ns = sum(parse_time_ns(r.get("Total Time (ns)", "0")) for r in rows)
        summary["total_kernel_time_ns"] = total_kern_ns
        summary["total_kernel_time_str"] = f"{total_kern_ns / 1e6:.3f} ms"
        summary["kernel_count"] = sum(int(r.get("Instances", "0")) for r in rows)
        summary["top_kernels"] = sorted(
            [
                {
                    "name": r.get("Name", "unknown"),
                    "total_ns": parse_time_ns(r.get("Total Time (ns)", "0")),
                    "instances": int(r.get("Instances", "0")),
                    "avg_ns": parse_time_ns(r.get("Avg (ns)", "0")),
                }
                for r in rows
            ],
            key=lambda x: x["total_ns"],
            reverse=True,
        )[:10]
    else:
        summary["total_kernel_time_ns"] = 0
        summary["kernel_count"] = 0
        summary["top_kernels"] = []

    # --- Memory transfer summary ---
    mem_path = os.path.join(stats_dir, "cuda_gpu_mem_time_sum.csv")
    if os.path.exists(mem_path):
        rows = parse_csv(mem_path)
        total_mem_ns = sum(parse_time_ns(r.get("Total Time (ns)", "0")) for r in rows)
        total_bytes = sum(parse_bytes(r.get("Total (Bytes)", "0")) for r in rows)
        summary["total_transfer_time_ns"] = total_mem_ns
        summary["total_transfer_time_str"] = f"{total_mem_ns / 1e6:.3f} ms"
        summary["total_transfer_bytes"] = total_bytes
        if total_mem_ns > 0:
            throughput = total_bytes / (total_mem_ns / 1e9)
            summary["transfer_throughput_gbs"] = throughput / 1e9
    else:
        summary["total_transfer_time_ns"] = 0
        summary["total_transfer_bytes"] = 0

    # --- API summary ---
    api_path = os.path.join(stats_dir, "cuda_api_sum.csv")
    if os.path.exists(api_path):
        rows = parse_csv(api_path)
        total_api_ns = sum(parse_time_ns(r.get("Total Time (ns)", "0")) for r in rows)
        summary["total_api_time_ns"] = total_api_ns

        # Find launch latency
        for r in rows:
            if "cudaLaunchKernel" in r.get("Name", ""):
                summary["avg_launch_latency_ns"] = parse_time_ns(r.get("Avg (ns)", "0"))
                summary["launch_count"] = int(r.get("Instances", "0"))
                break

        # Find malloc/free counts
        malloc_count = 0
        free_count = 0
        for r in rows:
            name = r.get("Name", "")
            if "cudaMalloc" in name and "Async" not in name:
                malloc_count += int(r.get("Instances", "0"))
            elif "cudaFree" in name and "Async" not in name:
                free_count += int(r.get("Instances", "0"))
        summary["cudaMalloc_count"] = malloc_count
        summary["cudaFree_count"] = free_count
    else:
        summary["total_api_time_ns"] = 0

    return summary


def format_summary(summary):
    """Format summary as markdown."""
    lines = []
    lines.append(f"# Profiling Summary: {summary.get('run_name', 'unknown')}\n")

    # Key ratios
    kern_ns = summary.get("total_kernel_time_ns", 0)
    mem_ns = summary.get("total_transfer_time_ns", 0)
    api_ns = summary.get("total_api_time_ns", 0)
    total_ns = kern_ns + mem_ns  # approximate GPU active time

    lines.append("## Key Metrics\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Kernel Time | {summary.get('total_kernel_time_str', 'N/A')} |")
    lines.append(f"| Kernel Count | {summary.get('kernel_count', 0)} |")
    lines.append(f"| Total Transfer Time | {summary.get('total_transfer_time_str', 'N/A')} |")

    if summary.get("transfer_throughput_gbs"):
        lines.append(f"| Transfer Throughput | {summary['transfer_throughput_gbs']:.2f} GB/s |")

    if summary.get("avg_launch_latency_ns"):
        lat_us = summary["avg_launch_latency_ns"] / 1000
        lines.append(f"| Avg Launch Latency | {lat_us:.2f} μs |")
        lines.append(f"| Launch Count | {summary.get('launch_count', 0)} |")

    if summary.get("cudaMalloc_count", 0) > 0:
        lines.append(f"| cudaMalloc Calls | {summary['cudaMalloc_count']} |")
        lines.append(f"| cudaFree Calls | {summary.get('cudaFree_count', 0)} |")

    # Ratios
    if kern_ns > 0:
        mem_ratio = mem_ns / kern_ns * 100
        lines.append(f"| Transfer/Kernel Ratio | {mem_ratio:.1f}% |")

    # Top kernels
    top_kernels = summary.get("top_kernels", [])
    if top_kernels:
        lines.append("\n## Top Kernels (by total time)\n")
        lines.append("| Kernel | Instances | Avg (μs) | Total (ms) | % of Total |")
        lines.append("|--------|-----------|----------|------------|------------|")
        for k in top_kernels:
            pct = k["total_ns"] / kern_ns * 100 if kern_ns > 0 else 0
            lines.append(
                f"| `{k['name'][:60]}` | {k['instances']} | "
                f"{k['avg_ns'] / 1000:.2f} | "
                f"{k['total_ns'] / 1e6:.3f} | "
                f"{pct:.1f}% |"
            )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Parse nsys stats CSV output")
    parser.add_argument("--stats-dir", required=True, help="Directory containing nsys stats CSVs")
    parser.add_argument("--run-name", default="", help="Name for this profiling run")
    parser.add_argument("--output", default=None, help="Output markdown file (default: stdout)")
    args = parser.parse_args()

    summary = analyze(args.stats_dir, args.run_name)
    report = format_summary(summary)

    if args.output:
        os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
        with open(args.output, "w") as f:
            f.write(report)
        print(f"Summary written to {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
